### ISSUE TITLE
Unexpected pauses when processing a lot of parallel jobs

### ISSUE THREAD

**Issue by dominikhorn93** [camunda-community-hub/spring-zeebe#171]
We have the problem that with a "large" number (1000) of parallel instances in a process, the worker loses the connection from time to time. We found out that the problem is probably caused by spring zeebe, because the same problem does not occur with the NodeJS worker. Because the connection is lost, the job in zeebe is blocked for x minutes and everything pauses. 

![Bildschirmfoto 2022-01-18 um 13 34 47](https://user-images.githubusercontent.com/27461050/149938278-4a1c4391-e4f9-4cdf-a8a6-c630f4a500f7.png)

Seems like it is a bit related to https://github.com/camunda-community-hub/spring-zeebe/issues/98.

There is a test project to reproduce the whole thing: https://github.com/FlowSquad/zeebe-benchmark
It includes a test project for Spring Zeebe and a test project for NodeJS 

Spring Zeebe (the break is between the two parallel activities)
![Screenshot from 2022-01-14 10-44-31](https://user-images.githubusercontent.com/27461050/149939353-a0e4e0ed-606f-49d3-a5fa-777c797a163b.png)

NodeJS:
![Screenshot from 2022-01-14 11-01-13](https://user-images.githubusercontent.com/27461050/149939381-cc4bc46f-305f-4c80-bfa5-959e933a8920.png)

Zeebe config: 
```

# Default values for zeebe-cluster-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Annotations to apply to the statefullset
annotations: {}

global:
  elasticsearch:
    disableExporter: true
    url:
    host: "elasticsearch-master.elastic.svc.cluster.local"
    port: 9200
  zeebe: "{{ .Release.Name }}-zeebe"
  zeebePort: 26500

image:
  repository: camunda/zeebe
  tag: 1.3.0
  pullPolicy: IfNotPresent

clusterSize: "3"
partitionCount: "9"
replicationFactor: "3"
cpuThreadCount: "2"
ioThreadCount: "2"
pvcSize: "10Gi"
pvcAccessModes: [ "ReadWriteOnce" ]
#env: []
logLevel: DEBUG

gateway:
  annotations: {}
  replicas: 2
  logLevel: DEBUG
  env: []
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable:
  priorityClassName: ""
  resources: {}
  serviceAccount:
    create: true
    name: ""
    annotations: {}

elasticsearch:
  enabled: false
  imageTag: 7.16.2

kibana:
  enabled: false
  imageTag: 7.16.2

prometheus:
  enabled: false
  servicemonitor:
    enabled: true

JavaOpts: >-
  -XX:MaxRAMPercentage=90
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
  -XX:+ExitOnOutOfMemoryError

#  
# -Xlog:gc*:/usr/local/zeebe/gc.log:time,level,tags

labels:
  app: zeebe
serviceType: ClusterIP
serviceGatewayType: ClusterIP
serviceHttpPort: 9600
serviceGatewayPort: 26500
serviceCommandPort: 26501
serviceInternalPort: 26502
priorityClassName: ""
resources:
  requests:
    cpu: 6
    memory: 12Gi
  limits:
    cpu: 8
    memory: 12Gi
probePath: /ready
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
podDisruptionBudget:
  enabled: false
  minAvailable:
  maxUnavailable: 1
podSecurityContext: {}
serviceAccount:
  create: true
  name: ""
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: {}
extraVolumeMounts: {}

# extraInitContainers: |
#   - name: init-exporters-hazelcast
#     image: busybox:1.28
#     command: ['/bin/sh', '-c']
#     args: ['wget --no-check-certificate https://repo1.maven.org/maven2/io/zeebe/hazelcast/zeebe-hazelcast-exporter/1.1.0/zeebe-hazelcast-exporter-1.1.0-jar-with-dependencies.jar -O /exporters/zeebe-hazelcast-exporter.jar; ls -al']
#     volumeMounts:
#     - name: exporters
#       mountPath: /exporters/
# env:
#   - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH
#     value: exporters/zeebe-hazelcast-exporter.jar
#   - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME
#     value: io.zeebe.hazelcast.exporter.HazelcastExporter
#   - name: ZEEBE_HAZELCAST_PORT
#     value: "5701"
#   - name: ZEEBE_HAZELCAST_REMOTE_ADDRESS
#     value: hazelcast.hazelcast.svc.cluster.local:5701
```
