### ISSUE TITLE
AutoComplete Option as property in application.yaml

### ISSUE THREAD

**Issue by mKrswe** [camunda-community-hub/spring-zeebe#456]
In our UseCase, we want to disable the autoComplete of the JobWorkers. As of now it is only possible to set it explicitly on every JobWorker.
An option could be to set the following option in the application.yaml:
```
zeebe:
  client:
    worker:
      auto-complete: false
```
or additionally

```
zeebe:
  client:
    worker:
      "<worker-name>":
        auto-complete: false
```
