### ISSUE TITLE
[8.5.0-rc2] Credentials provider priority

### ISSUE THREAD

**Issue by d4z4** [camunda-community-hub/spring-zeebe#754]
**Describe the bug**

Identity credentials provider is ignored when using these environment variables: ZEEBE_CLIENT_ID + ZEEBE_CLIENT_SECRET
A connection cannot be established with the selected legacy CredentialsProvider.

**To Reproduce**

Configure identity and use env variables ZEEBE_CLIENT_ID + ZEEBE_CLIENT_SECRET.

E.g.:
```yaml
camunda:
  client:
    mode: oidc
    auth:
      oidc-type: keycloak
      issuer: http://localhost:18080/auth/realms/camunda-platform
      client-id: ${ZEEBE_CLIENT_ID}
      client-secret: ${ZEEBE_CLIENT_SECRET}
    zeebe:
      enabled: true
      base-url: http://localhost:26500
      audience: zeebe-api
    identity:
      enabled: true
      base-url: http://localhost:8084
      audience: identity-api
```

**Expected behavior**

Configured identity credentials will be used.

**Log/Stacktrace**

https://github.com/camunda-community-hub/spring-zeebe/blob/ca6a98f6d51455c9d693811db8c4c28356a6a5ca/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfiguration.java#L239-L246

https://github.com/camunda-community-hub/spring-zeebe/blob/ca6a98f6d51455c9d693811db8c4c28356a6a5ca/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/configuration/PropertyUtil.java#L12-L23

LegacyProperties have a higher relevance. So the wrong (legacy) CredentialsProvider will be selected.

Currently, the environment variables have to be renamed to avoid this problem.

Would it be possible to change the relevance to: property,legacyProperty,defaultProperty?
Or maybe provide some kind of flag to disable legacy support.
