### ISSUE TITLE
Properties for self-managed camunda8 with identity, keycloak and TLS

### ISSUE THREAD

**Issue by cschaf** [camunda-community-hub/spring-zeebe#963]
Hi community,

I am struggeling to configurating the connection properties for a self-hosted camunda8 (v.8.5). Whould it be possible that someone could provide an template yaml or properties file for this szenario? Besides this, is there a list of all properties which I can configure in my yaml or properties file?

Greeting
Christian

**Comment by bbakker2** [comment]
Hi Christian,

We are struggling with the configuration as well. By coincidence "it worked on my machine", because I had legacy environment variables set. So our recipe for now is:
`application.yaml` :
```
camunda:
  client:
    mode: oidc
    tenant-ids:
    - my-tenant
    auth:
      oidc-type: keycloak
      issuer: https://keycloak-service.my-domain/realms/my-realm
      client-id: <REDACTED>
      client-secret: <REDACTED>
    zeebe:
      enabled: true
      gateway-url: http://localhost:26500
      base-url: http://localhost:8080
      prefer-rest-over-grpc: false
      audience: zeebe-api
    operate:
      enabled: true
      base-url: http://localhost:8081
      audience: operate-api
```
Plus environment variables:
```
export ZEEBE_CLIENT_ID=<REDACTED>
export ZEEBE_CLIENT_SECRET=<REDACTED>
export ZEEBE_AUTHORIZATION_SERVER_URL=https://keycloak-service.my-domain/realms/my-realm/protocol/openid-connect/token
```

Hope this helps!
